version: '3.6'

services:
  bothub-blog:
    image: ${BOTHUB_BLOG_DOCKER_IMAGE_NAME:-ilha/bothub-blog}:${BOTHUB_BLOG_DOCKER_IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80